### ISSUE TITLE
Document how to test the project

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/vue-testing-series#1]
This project is a working code samples for the serie [Write the first Vue.js Component Unit Test in Jest](https://alexjoverm.github.io/series/Unit-Testing-Vue-js-Components-with-the-Official-Vue-Testing-Tools-and-Jest/)

Mentioning to run `npm run test` or `npm t` to run the test, or with watch mode (`npm t -- --watch`) it's needed.

**Comment by zacck-zz** [comment]
@alexjoverm  will take this one

**Comment by alexjoverm** [comment]
Closed by #3
