### ISSUE TITLE
ERROR: Expected mock function to have been called

### ISSUE THREAD

**Issue by Zen33** [alexjoverm/vue-testing-series#14]
When I run the case below:
it('calls handleClick when click on message', () => {
  const stub = jest.fn()
  cmp.setMethods({ handleClick: stub })

  const el = cmp.find('.message').trigger('click')
  expect(stub).toBeCalled()
})

I get the following error.
except(jest.fn()).toBeCalled() Expected mock function to have been called. at Object...
I cannot figure out how to fix it, please help.

**Comment by alexjoverm** [comment]
Tests are being updated, this could be stale
