### ISSUE TITLE
Improve README docs

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/vue-testing-series#2]
This project is a working code samples for the serie [Write the first Vue.js Component Unit Test in Jest](https://alexjoverm.github.io/series/Unit-Testing-Vue-js-Components-with-the-Official-Vue-Testing-Tools-and-Jest/)

It'd be nice to have some documentation on this README describing what's this repo about in order to the user have some context

**Comment by Barathwaja** [comment]
Hi @alexjoverm , may I ??

**Comment by alexjoverm** [comment]
This issue still is open to add something that tells the users that is a code samples repo for the serie.

**Comment by komlew** [comment]
I'll take this one.

**Comment by komlew** [comment]
You'll probably need to update README file in the other branches as well. If you're fine with the changes  I made I'll create PRs to the other branches as well.

**Comment by alexjoverm** [comment]
Thanks a lot @komlew! I didn't have the time to do this, so you saved me here :)

Would you mind chaging the link to the series for the book's one? https://leanpub.com/testingvuejscomponentswithjest

And if you could link the image to that course that'd be really nice as well.

Thanks again, you're awesome!

**Comment by komlew** [comment]
Hey Alex! Sorry, you were faster than me. ;)
