### ISSUE TITLE
how to change mock response

### ISSUE THREAD

**Issue by jakecoffman** [alexjoverm/vue-testing-series#6]
in your axios mock example you return a promise, but how would you change what is returned so you can test a promise reject, different data, etc?

**Comment by alexjoverm** [comment]
Some things you can do:

 - You can improve that mock having a common behaviour that behaves as you wish. That axios example is very short to show the feature. An idea: make even calls resolve, odd fail. Another idea: depending on some condition (calling some endpoint), it should return something else
 - If you need different behaviour depending on the test, that's something you must implement on each test. Jest gives you ways using it's [mocking API](https://facebook.github.io/jest/docs/en/mock-functions.html#mock-implementations)
