### ISSUE TITLE
Book not up to date with the source

### ISSUE THREAD

**Issue by mikebonds** [alexjoverm/vue-testing-series#7]
I bought your book as I wanted to support your blog, and be able to read about testing Vue with jest more easily while on the go. I decided to go through the first part of the book, but noticed the the book seams to be out of sync with the source here. I am wondering if you plan on updating the book, or if it was an assumption that people would check the full example to figure out why they are running into issues.

**Comment by alexjoverm** [comment]
Hi @mikebonds!

They could be a bit out of sync, specially in the opposite direction (book-to-code). As I was updating both the content and the code as I was finding out things, probably some stuff in the code wasn't updated accordingly.

Could you tell me of some specific part where you find it out of sync, so we can update it here? Thanks!

**Comment by mikebonds** [comment]
I think it mostly had to do with the package.js. To be honest, I can't fully remember. I am working in a Laravel environment that required a little extra setup. Your book has been very helpful though!

`
"jest": {
    "moduleNameMapper": {
      "@/([^\\.]*).vue$": "<rootDir>/src/$1.vue",
      "@/([^\\.]*)$": "<rootDir>/src/$1.js",
      "^vue$": "vue/dist/vue.common.js"
    },
    "moduleFileExtensions": [
      "js",
      "vue"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.(vue)$": "<rootDir>/node_modules/jest-vue-preprocessor"
    }
  }
`

In the book, that was setup a little differently.

**Comment by alexjoverm** [comment]
The contents are being updated right now
