### ISSUE TITLE
non-prop attributes would be still set in the component.

### ISSUE THREAD

**Issue by LucienLee** [alexjoverm/vue-testing-series#8]
In _Test Properties and Custom Events_ section, the following test would be wrong

```js
// https://github.com/alexjoverm/vue-testing-series/blob/Test-Properties-and-Custom-Events-in-Vue-js-Components-with-Jest/test/Message.test.js#L17

it('has no cat property', () => {
  cmp = createCmp({ cat: 'hey', message: 'hey' })
  expect(cmp.hasProp('cat', 'hey')).toBeFalsy() <- would be true
})
```
The reason that vue treat it as [Non-Prop-Attributes](https://vuejs.org/v2/guide/components.html#Non-Prop-Attributes) and inject it into the root of component. In addition, the mount fake the instance, so the root is the component itself.

**Comment by alexjoverm** [comment]
Fixed on the blog and on this repo https://alexjoverm.github.io/2017/09/11/Test-Properties-and-Custom-Events-in-Vue-js-Components-with-Jest/. In a future I'll realease a new version of the book, thanks!
